### ISSUE TITLE
FFXIVAPP for v2.38

### ISSUE THREAD

**Issue by x334519339** [Icehunter/ffxivapp#37]
Where can I get the ffxivapp for FFXIV 2.38？The last verison update is likely not to work...

thanks

**Comment by Icehunter** [comment]
Is that the official Chinese version?

The application right now only works for 2.5 (NA/JA/EU) as we have a different client altogether. I think we are on different patches?

Ours is this:
![image](https://cloud.githubusercontent.com/assets/677341/6073668/2a3991de-ad66-11e4-8fda-2e5a8cff08d5.png)

I'm working on finding a way to register for Shanda games and making this one work for the Chinese version but it's getting a little difficult being outside the country.

**Comment by x334519339** [comment]
Yes，it's the offical Chinese verison.

I think the Chinese verison may be the patch 2.3（Defenders of Eorzea）. And the ACT v1.3.0.7（Advanced Combat Tracker） can work on the Chinese client.

If the memory signatures of the Chinese verison is same to the FFXIV v2.3. Can ffxivapp work on it？

thanks.

**Comment by Icehunter** [comment]
I believe so. Can you try an old copy of this application here:

https://github.com/Icehunter/ffxivapp/releases/tag/3.0.5373.34340

Please keep in mind the parser is only designed for the other 4 languages, but after installing this one install a few plugins like Radar, Widgets, Log and see if any data shows up.

If it does than it will work and maybe I have to make branches off of everything and maintain 2 copies. One for the Chinese version and one for the rest.

Thanks!

**Comment by x334519339** [comment]
I'll try it after my working. 

Thank you very much！ヾ(*´∀｀*)ﾉ

**Comment by Icehunter** [comment]
The parser does not work though? :) I'm hoping to make it compatible with the the Chinese language option as well.

**Comment by x334519339** [comment]
If I chang the system locale setting to the specified language. Can the parser work？

**Comment by x334519339** [comment]
The old copy of this application can work. But plugins like Radar and Parser is no data shows up...
_(:зゝ∠)_

**Comment by Icehunter** [comment]
Okay :( Will I be able to register for shanda games/ffxiv if I'm not a citizen of China? If I can register for the game and pay for it then I can install it on my computer and get a version ready that supports the Chinese version.

**Comment by x334519339** [comment]
Can you give me your e-mail ? I have a paid Shanda account and send to your e-mail.

**Comment by Icehunter** [comment]
You can send a email through here actually:

google.com/+RyanWilson

I can respond to that :)

Thanks!

**Comment by x334519339** [comment]
I have send a email to you. pls check~

**Comment by Icehunter** [comment]
Hmm, did not go through. Please try using this one: syndicated.life@gmail.com; as it's the email on my main profile. Google might have blocked requests from my g+ page.

**Comment by x334519339** [comment]
Ok. I have send it

**Comment by Icehunter** [comment]
Thanks! Already pushing code up to support the changes :)

**Comment by x334519339** [comment]
The ffxivapp can work. But the parse seems that is not to work. 
And how to make the plugins display always on top? Can the Radar's detection rang be change?

Thanks :)

**Comment by Icehunter** [comment]
Parsing is going to take a while however someone just contacted me to help get that running.

Always on top uses "window title" to find FFXIV. Because It's only coded for the JA/NA/EU client I need to know what the title is in Chinese.

Example:
https://github.com/Icehunter/ffxivapp-plugin-parse/blob/master/FFXIVAPP.Plugin.Parse/Helpers/WidgetTopMostHelper.cs#L103

I noticed when I ran the client from shanda that it has ????XIV. I hadn't turned my windows locale to Chinese yet. Do you know what that window title is?  :)

The detection range at this time can't be changed as it only renders what you see in-game.

I hopefully with further testing will be releasing a version of the radar which can "link" together other radars from the server and make a server wide radar.

**Comment by x334519339** [comment]
Yes, the windows title is "最终幻想XIV".

**Comment by Icehunter** [comment]
Updated along with some merge requests. There's still some fine tuning and I will be getting the UI translated to Mandarin pretty quickly I think.
