### ISSUE TITLE
Server Missing

### ISSUE THREAD

**Issue by mrdee81** [Icehunter/ffxivapp#39]
Maybe this is not an issue as you can just enter your lodestone ID but I noticed that the Jenova Server is not in this app. I know this is only a small issue but under character settings, should you not have all the servers? 

Thank you for reading ^^

**Comment by Icehunter** [comment]
I'm in the process of adding that. I'm actually working on having the app and plugins work the the Chinese client as well.

Thanks!

**Comment by Icehunter** [comment]
Update released with server name. Let me know if that worked for you :)

**Comment by mrdee81** [comment]
Worked perfectly. Thank you very much ^__^
