### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by loveforlife** [Icehunter/ffxivapp#40]
Hey i resent downloaded it and started to use it was great, But the problem i been having is that i closed the widgets thinking when i started up the program again it would pop up. When i restarted the program again there was no widget that poped up for dsp hps or dts. Several other widgets like twin and enmity work fine but i fail to find the button to pull out the widget for dsp hsp and dts to appear over my game over the . I recently re-downloaded it to see if that was the original problem but found it never would pull up that widget again even after several reattempts.

**Comment by Icehunter** [comment]
You will find those in then plugin for parse now. Settings/Main.

I had moved them out into there. Sorry!
