### ISSUE TITLE
FFXIV-APP Won't open

### ISSUE THREAD

**Issue by LagunaLoire** [Icehunter/ffxivapp#51]
Using Windows 8, .NET is 4.5 and I am running as admin each time I attempted to open it. I have now deleted every trace of it, re downloaded, extracted with WINRAR and tried again and still all it does is spin the little blue loading circle on the cursor then... nothing. The app was working fine yesterday until I shut down my laptop. Upon rebooting FFXIV-APP refuses to do anything. I'd also attempted the Updater exe but again nothing happens. Running in Win 7 Compat mode also doesn't change it.

**Comment by LagunaLoire** [comment]
Oh, also I had made sure to delete the My Docs folder too when doing a total refresh of the app. Attempting the launch the freshly downloaded app can't even create the folders in my doc, even if it is run as admin

**Comment by Icehunter** [comment]
After re-downloading it right click the zip file -> properties -> unblock.

There's also a file under your AppData folder -> Local -> SyndicatedLife.

If you delete that folder it clears at ALL application preferences. You can backup that one if you prefer just in case.

Typically the error that you are receiving is a data error in a config file somewhere.

**Comment by LagunaLoire** [comment]
Thanks that got it working. If anybody else was having the same issue, I tried each thing 1 at a time - the App Data folder had a corrupted file somewhere so that was the one that needed cleaning up

**Comment by Icehunter** [comment]
That file is only used for the "main" application settings and doesn't store plugin settings. I'll investigate what other things could cause corruption.

Thanks!
