### ISSUE TITLE
Client not working/blank white screen

### ISSUE THREAD

**Issue by jcade-sim7447** [Icehunter/ffxivapp#52]
Hi Icehunter, 

Last night I was notified of an update to the app.
After running said update, the app is completely without functionality now. 
This is what I see: http://gyazo.com/f0347063e142c80cee57a6cb9b5bc679
I'm not sure if it's anything to do with the build update you pushed a day or two ago, but it seems to be the case because I had no troubles beforehand with the app.
I've double checked that the program is allowed through my antivirus and firewall, double-checked that .Net 4.5 is installed, as well as completely deleting everything and starting fresh with the latest version - all to no avail.

Any assistance would be appreciated.

**Comment by Icehunter** [comment]
http://ffxiv-app.com/topic/23/3-0-5591-32096/5

I've sent out notifications to the other devs about this. If you have something custom you will have to do the same thing as well. Sorry :(

**Comment by jcade-sim7447** [comment]
Aha! The one thing I hadn't tried. Now I know.
Thank you and thanks for the wonderful app!

**Comment by Icehunter** [comment]
You're welcome :)
