### ISSUE TITLE
Latest update to the Gathering Plugin wipes out the interface

### ISSUE THREAD

**Issue by LagunaLoire** [Icehunter/ffxivapp#53]
So I opened the app today and was greeted by the blue bar at the top, then nothing but white under it. I cleared the AppData, Download and My Doc folder of FFIV APP, re downloaded, installed and the interface was back. As son as I installed the Gathering Plugin and restarted the app, it had gone back to white. Something in the update obviously went very wrong.

Screenshot of app without interface:
http://imgur.com/mgOWvVC.

**Comment by Icehunter** [comment]
I reported the issue to the other plugin developers as the UI framework DLL had a version update.

https://github.com/Icehunter/ffxivapp/issues/52
http://ffxiv-app.com/topic/23/3-0-5591-32096/5

As soon as they fix it it will work again. The gathering one is from a developer in Japan so they may be still sleeping depending on schedule.
