### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by tox8ik** [Icehunter/ffxivapp#73]
Feature:
Can we get Windows 10 support please?

**Comment by Icehunter** [comment]
It's supported Windows 10 since release but if you mean DX11 I'm still working on it. :(

**Comment by tox8ik** [comment]
Oh okay I was looking at the FAQ "requirements" section to find out why I couldn't get it to work and it didn't show Windows 10 so I figured that was the culprit.  Alright then, I love what you do sir. Please keep up the good work. I will patiently wait for the DX11 update.  Thank you.
